name: metapool
channels:
  - bioconda
  - conda-forge
  - ccbbucsd
  - r
  - defaults
dependencies:
  - notebook
  - jupyter
  - pep8
  - seaborn[version='>=0.7.1']
  - matplotlib
  - openpyxl
  - pandas
  - numpy
  - pip
  - python=3.9
  - seqtk[version='>=1.4']
  - nose
  - scikit-learn
  - biom-format
  - flake8
  - pip:
      - click
      - coverage
      - coveralls
      - jupyter_contrib_nbextensions
      - ipykernel
      - sample-sheet
      - watermark